### ISSUE TITLE
I wanted to add Face Recognition Project developed using OpenCV Module in Python

### ISSUE THREAD

**Issue by mrghost100348** [Techiral/A-Z-Python-Projects#4]
Face Recognition Project developed using OpenCV Module in Python. This Display a Blue Reactangle Frame around Faces. Please assign me and check pull request section for details.

**Comment by Techiral** [comment]
You can add but don't forget to add your name in ReadMe.md in the Contributors Section.

**Comment by Techiral** [comment]
Done
