### ISSUE TITLE
To Create Chat GPT based Voice Assistant

### ISSUE THREAD

**Issue by ezhillragesh** [Techiral/A-Z-Python-Projects#79]
To make use of openai api to develop a voice assistant which can also listen to your voice and then reply

**Comment by ezhillragesh** [comment]
I would like to contribute for this project @Techiral can you assign this to me for my Hacktoberfest contribution ?

**Comment by Techiral** [comment]
@ezhillragesh Sure, I'd be happy to have you contribute to this project for Hacktoberfest! 🎉 Feel free to fork the repository and work on implementing the voice assistant features using the OpenAI API. Once you're ready, submit a pull request with your changes, and we'll review and merge it. If you have any questions or need assistance, don't hesitate to ask. Looking forward to your contributions! 🚀
