### ISSUE TITLE
Adding KBC Game in Python

### ISSUE THREAD

**Issue by joshiadarshx** [Techiral/A-Z-Python-Projects#89]
I want to add simple  KBC game  made using  PYthon in this repo. 
Maintainers can you please assign this issue to me

**Comment by Techiral** [comment]
@joshiadarshx  Sure, I'd be happy to have you contribute to this project for Hacktoberfest! 🎉 Feel free to fork the repository and work on implementing the voice assistant features using the OpenAI API. Once you're ready, submit a pull request with your changes, and we'll review and merge it. If you have any questions or need assistance, don't hesitate to ask. Looking forward to your contributions! 🚀

**Comment by joshiadarshx** [comment]
> @joshiadarshx Sure, I'd be happy to have you contribute to this project for Hacktoberfest! 🎉 Feel free to fork the repository and work on implementing the voice assistant features using the OpenAI API. Once you're ready, submit a pull request with your changes, and we'll review and merge it. If you have any questions or need assistance, don't hesitate to ask. Looking forward to your contributions! 🚀
I am really new to python and this opensource I don't think that I will be able to add a voice assistant features in this small mini project . Will it not be accepted?sir @Techiral
